apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ortelius
  namespace: argocd
spec:
  destination:
    namespace: ortelius
    server: https://kubernetes.default.svc
  project: ortelius
  source:
    path: argocd/manifests/ortelius
    repoURL: https://github.com/piomin/sample-terraform-kubernetes-argocd.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true