apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keptn
  namespace: argocd
spec:
  destination:
    namespace: keptn
    server: https://kubernetes.default.svc
  project: keptn
  source:
    path: argocd/manifests/cluster
    repoURL: https://github.com/ortelius/ortelius-charts.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
