apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ortelius
  namespace: argocd
spec:
  destination:
    namespace: ortelius
    server: https://kubernetes.default.svc
  project: ortelius
  source:
    path: argocd/argo-apps/ortelius
    repoURL: https://github.com/ortelius/ortelius
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
