apiVersion: v1
kind: ConfigMap
metadata:
  name: github-oauth-switch
data:
  # String "True" or "False"
  GITHUB_OAUTH_ENABLED: "{{ .Values.oauth_enabled }}"
  # Space separated github team slugs within azt-grl org
  OAUTH2_ALLOWED_TEAMS: "{{ .Values.oauth2_allowed_teams }}"
  # either one of the accounts we have . infra, nonprod, preprod, common or prod.
  # This variable is for templating the proxy hostname.
  cluster: {{ template "acmaccount" $ }}
